CREATE TABLE EMPLOYEES (EMPLOYEE_ID INT PRIMARY KEY, EMPLOYEE_NAME varchar(50) NOT NULL, GENDER varchar(50) NOT NULL, CLIENT_NAME varchar(50), MARITAL_STATUS varchar(50) NOT NULL, DEPARTMENT varchar(50),YEARS_IN_ORG INT DEFAULT 0, DATE_OF_JOINING DATE NOT NULL, PERFORMANCE_MANAGER varchar(50) NOT NULL, REPORTING_MANAGER varchar(50));

CREATE TABLE ABSENCES_DETAILS (ABSENCES_DETAILS_ID INT PRIMARY KEY, EMPLOYEE_ID INT NOT NULL, TOTAL_LEAVES INT DEFAULT 0, ANNUAL_LEAVES INT DEFAULT 0, SICK_LEAVES INT DEFAULT 0, FLEXI_LEAVES INT DEFAULT 0);

CREATE TABLE ABSENTS (ABSENT_ID INT PRIMARY KEY, ABSENCES_DETAILS_ID INT REFERENCES ABSENCES_DETAILS(ABSENCES_DETAILS_ID),  ABSENT_TYPE varchar(50) NOT NULL, DAYS INT DEFAULT 0, PROJECTCODE INT NOT NULL, FROM_DATE DATE NOT NULL, TO_DATE DATE NOT NULL, APPROVAL_STATUS BOOLEAN DEFAULT FALSE);

CREATE TABLE WORKSHEET_DETAILS (WSDETAILS_ID INT PRIMARY KEY, EMPLOYEE_ID INT NOT NULL, MONTH_VALUE varchar(50) NOT NULL);

CREATE TABLE WORKSHEET (WORKSHEET_ID INT PRIMARY KEY, WSDETAILS_ID INT REFERENCES WORKSHEET_DETAILS(WSDETAILS_ID), WORK_STATUS varchar(50) NOT NULL, NO_OF_HOURS INT DEFAULT 0, PROJECT_CODE INT NOT NULL, DATE DATE NOT NULL);

